### ISSUE TITLE
Traceback with crafting.py

### ISSUE THREAD

**Issue by Linderoth** [skatje-myers/stardewscripts#2] opened 2017-01-22 19:35 UTC
With python 3.6.0 I'm having a Traceback error with crafting.py

`Traceback (most recent call last):
  File "D:\Software\stardewscripts-master\crafting.py", line 163, in <module>
    main()
  File "D:\Software\stardewscripts-master\crafting.py", line 130, in main
    name = item.find('Name').text
AttributeError: 'NoneType' object has no attribute 'text'`

Thank you

**Comment by skatje-myers** [comment] 2017-03-04 10:11
I haven't been able to reproduce this. I know it's been a while since you reported this, but could you provide me a save file that causes this error?

**Comment by ghost** [comment] 2017-03-28 09:04
I get the same error with python 3.6.0:

```Traceback` (most recent call last):
  File "crafting.py", line 163, in <module>
    main()
  File "crafting.py", line 130, in main
    name = item.find('Name').text
AttributeError: 'NoneType' object has no attribute 'text'```

I've attached the corresponding savegame. Thanks for your help!

[Philipp_147466321.zip](https://github.com/skatje-myers/stardewscripts/files/875058/Philipp_147466321.zip)

**Comment by skatje-myers** [comment] 2017-03-28 16:56
Thanks for the save file. It's fixed now.

**Closed as completed by skatje-myers** 2017-03-28 16:56 UTC
